-- FIRST(NORMAL FROM )
DROP TABLE IF EXISTS STUDENT2;
CREATE TABLE STUDENT2
(
   "ID" INT PRIMARY KEY,
   "NAME" VARCHAR(50),
   "AGE" INT,
   "COURSE" VARCHAR(30),
   "FEES" NUMERIC
);

insert into STUDENT2 values(1, 'Abhay Singh', 20, 'SQl', 8000);
insert into STUDENT2 values(2, 'Anand Ray', 20, 'SQl', 8000);
insert into STUDENT2 values(3, 'Kunal singh', 20, 'SQl', 8000);

SELECT * FROM STUDENT2;

drop table STUDENT2;


--SECOND
DROP TABLE IF EXISTS STUDENT2;

CREATE TABLE STUDENT2
( 
     "ID" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	 "NAME"VARCHAR(50),
	 "AGE" INT,
	 "COURSE" VARCHAR(30),
	 "FEES" NUMERIC
);

insert into STUDENT2 values(DEFAULT, 'Himesh Singh', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Parv Ray', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Durgesh singh', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Kunal singh', 30, 'SQl', 8000);

SELECT *FROM Student2;

--THIRD ((IT IS NOT COMPLETLY WORK BECOUSE I USE "GENARTED ALWAYS " COMMAND))

DROP TABLE IF EXISTS STUDENT2;

CREATE TABLE STUDENT2
( 
     "ID" INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	 "NAME"VARCHAR(50),
	 "AGE" INT,
	 "COURSE" VARCHAR(30),
	 "FEES" NUMERIC
);

insert into STUDENT2 values(DEFAULT, 'Himesh Singh', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Parv Ray', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Durgesh singh', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Kunal singh', 30, 'SQl', 8000);
insert into STUDENT2 values(30, 'Kunal singh', 30, 'SQl', 8000);          --IT CREATING A ERROR COUSE ID = 30 .

SELECT *FROM Student2;



-- FOURTH (IT IS COMPLETLY WORK BECOUSE I USE "BY DEFAULT ", COMMAND)

DROP TABLE IF EXISTS STUDENT2;
CREATE TABLE STUDENT2
(
  "ID" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	 "NAME"VARCHAR(50),
	 "AGE" INT,
	 "COURSE" VARCHAR(30),
	 "FEES" NUMERIC
);

insert into STUDENT2 values(DEFAULT, 'Himesh Singh', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Parv Ray', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Durgesh singh', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Kunal singh', 30, 'SQl', 8000);
insert into STUDENT2 values(30, 'Kunal singh', 30, 'SQl', 8000); 

SELECT *FROM Student2;


-- FIFTH( COMPLETLY RUN )
DROP TABLE IF EXISTS STUDENT2;
CREATE TABLE STUDENT2
(
  "ID" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  				(START WITH 10 INCREMENT 1),
	 "NAME" VARCHAR(50),
	 "AGE" INT,
	 "COURSE" VARCHAR(30),
	 "FEES" NUMERIC
);

insert into STUDENT2 values(DEFAULT, 'Himesh Singh', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Parv Ray', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Durgesh singh', 20, 'SQl', 8000);
insert into STUDENT2 values(DEFAULT, 'Kunal singh', 30, 'SQl', 8000);
insert into STUDENT2 values(30, 'Kunal singh', 30, 'SQl', 8000); 

SELECT *FROM Student2;


